### ISSUE TITLE
[Feature request] Support for long-read data

### ISSUE THREAD

**Issue by Vini2** [Vini2/phables#8]
**Is your feature request related to a problem? Please describe.**
Currently, long-read data are not fully utilised by phables.

**Describe the solution you'd like**
Allow the option to select between long-read and short-read data when running phables.

**Points to note in development**
Keep track of unitigs aligning to long reads and create relevant subpaths with read counts.

**Comment by alegarritano** [comment]
Hi @Vini2,

Thanks for developing the tools, it seems very promising. 
Unfortunately, I am facing an error when trying to run it. "phables test" runs fine, but I am trying to use it with long-read data, and the software crashes just after I run it. 

I noticed that you say long-read data is not fully utilised, but I am wondering if the software is compatible with long-read data at the moment and some information is not used or if it's not compatible at all and this is a glitch on my end. 

This is the error:

[2023:12:07 21:50:46] ---------------------
[2023:12:07 21:50:46] | Snakemake command |
[2023:12:07 21:50:46] ---------------------

snakemake -s mypython3env_Phables/lib/python3.11/site-packages/phables/workflow/phables.smk --configfile phables.out/config.yaml --cores 36 --use-conda --conda-prefix mypython3env_Phables/lib/python3.11/site-packages/phables/workflow/conda --rerun-incomplete --printshellcmds --nolock --show-failed-logs
Set parameter WLSAccessID
Set parameter WLSSecret
Set parameter LicenseID to value 2450061
Academic license 2450061 - for non-commercial use only - registered to al___@unsw.edu.au
mypython3env_Phables/lib/python3.11/site-packages/pulp/apis/gurobi_api.py:170: UserWarning: GUROBI error: Unknown parameter '_test'.
  warnings.warn("GUROBI error: {}.".format(e))
Config file mypython3env_Phables/lib/python3.11/site-packages/phables/workflow/../config/config.yaml is extended by additional config specified via the command line.
Config file mypython3env_Phables/lib/python3.11/site-packages/phables/workflow/../config/databases.yaml is extended by additional config specified via the command line.
Output files will be saved to directory, phables.out

IndexError in file mypython3env_Phables/lib/python3.11/site-packages/phables/workflow/rules/02_phables_preflight.smk, line 23:
list index out of range
  File "mypython3env_Phables/lib/python3.11/site-packages/phables/workflow/phables.smk", line 16, in <module>
  File "mypython3env_Phables/lib/python3.11/site-packages/phables/workflow/rules/02_phables_preflight.smk", line 23, in <module>
  File "mypython3env_Phables/lib/python3.11/site-packages/metasnek/fastq_finder.py", line 196, in parse_samples_to_dictionary
  File "mypython3env_Phables/lib/python3.11/site-packages/metasnek/fastq_finder.py", line 140, in parse_samples
  File "mypython3env_Phables/lib/python3.11/site-packages/metasnek/fastq_finder.py", line 95, in parse_tsv_file

Thanks,

**Comment by Vini2** [comment]
Hi @alegarritano,

Thanks for your interest in Phables. 

Currently Phables does not support long-read data. I'm planning to add support in the next few months. I'll let you know once it's implemented. 

Thanks!
